### ISSUE TITLE
Different from Core Foundry

### ISSUE THREAD

**Issue by 9ryex5** [caewok/fvtt-walled-templates#1]
Without any walls on the scene, this module draws cones and circles differently from Core Foundry.

![image](https://user-images.githubusercontent.com/43207603/147910289-74d02cba-2948-4973-953d-c6ddcf97347c.png)

**Comment by caewok** [comment]
Fixed by [v 0.2.0](https://github.com/caewok/fvtt-walled-templates/releases/tag/0.2.0). 

There could still be variations from Core Foundry because when Core determines which grid squares are highlighted, it is comparing against the concept of a circle (radius + center point) while the walled template must rely on an approximation of the circle using a polygon. This approximation can be slightly off, which can make a big difference in what edge grid squares are included. That said, I think I have matched what should happen in the no-wall versions for the current Core templates.

For example, this image is actually of the Foundry circle (blue) with the walled-template version (red) laid over top. They look identical, but are not in fact identical:
<img width="305" alt="Screen Shot 2022-05-09 at 3 04 09 PM" src="https://user-images.githubusercontent.com/1267134/167702642-587cf9b0-0e51-4325-a780-74809de4b597.png">

If you find other cases where the templates appear off from what you would expect in Core, please let me know and I can see if I can tweak the algorithm further.
