### ISSUE TITLE
Request: Wall Height compatibility

### ISSUE THREAD

**Issue by Zamrod** [caewok/fvtt-walled-templates#15]
Right now with Wall Height enabled the template will go right through any wall that has a height listed. It only wraps around infinity height walls.

**Comment by caewok** [comment]
Fixed in v0.4.4. I added an elevation setting in the MeasuredTemplate config. (This is the same setting as what Levels uses, and should default back to the Levels version if that module is installed.) 

Figuring out what elevation a given template should be at is a bit tricky. Right now, it is defaulting to the current combatant's elevation if the combatant is controlled by the user. Otherwise it defaults to the last controlled token for that user. (This is more complicated than it sounds because Foundry doesn't track this and de-selects tokens when you change layer controls.). If all else fails, it defaults to 0 elevation.

You can go into the config for the template to change the elevation if necessary. 

With elevation set, Wall Height walls should block templates as expected, depending on elevation.
