### ISSUE TITLE
Bugged with Token Magic FX

### ISSUE THREAD

**Issue by GambetTV** [caewok/fvtt-walled-templates#6]
When combined with MidiQOL and Token Magic FX, templates will visually be stopped by walls, but will still target tokens within its radius range but through walls. It works fine with MidiQOL by itself, but adding Token Magic FX to the mix seems to mess it up.

![image](https://user-images.githubusercontent.com/72000497/169454883-85bb8fa3-aff1-4ab5-bd15-89f81a852a8e.png)

**Comment by caewok** [comment]
I took a quick look at MidiQOL and Token Magic FX. I think this works if you use v0.3.0 of Walled Templates. 
- In MidiQOL Workflow settings, set "Autotarget on template draw" to either "Always" or "Always - ignore defeated." This forces MidiQOL to wait for you to place the template. ("None" doesn't work, because it doesn't wait. You probably don't want the "walls block" versions because Walled Templates is going to take over that work instead.)
- In Walled Templates settings, you obviously want to enable autotargeting. In this case, you probably also want to enable "walls block". Note that you can enable/disable "walls block" for a specific spell in the spell settings. 

For me, this seems to work with or without Token Magic FX, and the tokens are targeted as you would expect. Even better, because Walled Templates targets as you drag the template, it is a bit easier to see what is or is not targeted.

**Comment by GambetTV** [comment]
Switching Walled Template to Always Autotarget fixed the issue! Thanks!
