### ISSUE TITLE
Example of rectangle polygon failing with error

### ISSUE THREAD

**Issue by caewok** [caewok/fvtt-walled-templates#68]
https://ptb.discord.com/channels/915186263609454632/1107502968179273778/1155946687341285397

**Comment by mcabel** [comment]
this may be related, since rectangle gives me errors:

`<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto; color: rgb(227, 227, 227); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/modules/walledtemplates/scripts/geometry/RegularPolygon/Square.js:67" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">Square.js:67</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: Cannot destructure property 'width' of 'token.hitArea' as it is null.
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Square.fromToken (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/modules/walledtemplates/scripts/geometry/RegularPolygon/Square.js:67:13" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">Square.js:67:13</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at tokenBounds (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/modules/walledtemplates/scripts/util.js:73:17" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">util.js:73:17</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at showHideTemplates (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/modules/walledtemplates/scripts/Token.js:364:19" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">Token.js:364:19</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at CONFIG.Token.objectClass._onHoverIn (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/modules/walledtemplates/scripts/Token.js:342:3" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">Token.js:342:3</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at 🎁CONFIG.Token.objectClass.prototype._onHoverIn#0 (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/modules/lib-wrapper/src/lib/libWrapper-wrapper.js:187:52" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">libWrapper-wrapper.js:187:52</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at MouseInteractionManager.callback (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/scripts/foundry.js:30823:17" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">foundry.js:30823:17</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at #handlePointerOver (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/scripts/foundry.js:30925:15" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">foundry.js:30925:15</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at vh.notifyListeners (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/packages/events/src/EventBoundary.ts:1454:26" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">EventBoundary.ts:1454:26</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at vh.notifyTarget (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/packages/events/src/EventBoundary.ts:662:18" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">EventBoundary.ts:662:18</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at vh.propagate (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/packages/events/src/EventBoundary.ts:299:14" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">EventBoundary.ts:299:14</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at vh.dispatchEvent (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/packages/events/src/EventBoundary.ts:210:14" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">EventBoundary.ts:210:14</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at vh.mapPointerMove (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/packages/events/src/EventBoundary.ts:770:18" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">EventBoundary.ts:770:18</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at vh.mapEvent (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/packages/events/src/EventBoundary.ts:231:28" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">EventBoundary.ts:231:28</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at ra.onPointerMove (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/packages/events/src/EventSystem.ts:396:31" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">EventSystem.ts:396:31</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at MouseInteractionManager.&lt;anonymous&gt; (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/scripts/foundry.js:30732:23" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">foundry.js:30732:23</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/scripts/foundry-esm.js:2718:18" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">foundry-esm.js:2718:18</span></span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(227, 227, 227); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace stack-preview-container" style="display: inline-block; width: 361.4px; --monospace-font-size: 12px; --monospace-font-family: consolas,lucida console,courier new,monospace; --source-code-font-size: 12px; --source-code-font-family: consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | fromToken | @ | Square.js:67
-- | -- | -- | --
  | tokenBounds | @ | util.js:73
  | showHideTemplates | @ | Token.js:364
  | _onHoverIn | @ | Token.js:342
  | 🎁CONFIG.Token.objectClass.prototype._onHoverIn#0 | @ | libWrapper-wrapper.js:187
  | callback | @ | foundry.js:30823
  | #handlePointerOver | @ | foundry.js:30925
  | notifyListeners | @ | EventBoundary.ts:1454
  | notifyTarget | @ | EventBoundary.ts:662
  | propagate | @ | EventBoundary.ts:299
  | dispatchEvent | @ | EventBoundary.ts:210
  | mapPointerMove | @ | EventBoundary.ts:770
  | mapEvent | @ | EventBoundary.ts:231
  | onPointerMove | @ | EventSystem.ts:396
  | (anonymous) | @ | foundry.js:30732
  | (anonymous) | @ | foundry-esm.js:2718
  | setTimeout (async) |   |  
  | (anonymous) | @ | foundry-esm.js:2715
  | emulateMoveEvent | @ | foundry.js:30724
  | (anonymous) | @ | foundry.js:26717
  | Promise.finally (async) |   |  
  | draw | @ | foundry.js:26701
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:507
  | tokenDraw | @ | monks-active-tiles.js:2483
  | 🎁call_wrapper | @ | libWrapper-wrapper.js:616
  | 🎁Token.prototype.draw#0 | @ | libWrapper-wrapper.js:189
  | (anonymous) | @ | foundry.js:34296
  | map | @ | foundry-esm.js:5098
  | _draw | @ | foundry.js:34293
  | await in _draw (async) |   |  
  | _draw | @ | foundry.js:41582
  | (anonymous) | @ | foundry.js:33712
  | Promise.finally (async) |   |  
  | draw | @ | foundry.js:33709
  | _draw | @ | foundry.js:28263
  | await in _draw (async) |   |  
  | _draw | @ | foundry.js:50656
  | (anonymous) | @ | foundry.js:28247
  | Promise.finally (async) |   |  
  | draw | @ | foundry.js:28244
  | #draw | @ | foundry.js:25051
  | Promise.finally (async) |   |  
  | draw | @ | foundry.js:24936
  | view | @ | foundry.js:21358
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:507
  | sceneView | @ | monks-scene-navigation.js:608
  | 🎁call_wrapper | @ | libWrapper-wrapper.js:616
  | 🎁Scene.prototype.view#0 | @ | libWrapper-wrapper.js:189
  | initializeCanvas | @ | foundry.js:9270
  | await in initializeCanvas (async) |   |  
  | setupGame | @ | foundry.js:9081
  | await in setupGame (async) |   |  
  | _initializeGameView | @ | foundry.js:10431
  | _initializeView | @ | foundry.js:10407
  | initialize | @ | foundry.js:8994
  | await in initialize (async) |   |  
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:507
  | 🎁libWrapperInit | @ | libWrapper-api.js:805
  | await in 🎁libWrapperInit (async) |   |  
  | 🎁Game.prototype.initialize#0 | @ | libWrapper-wrapper.js:187
  | window.addEventListener.once | @

</span></div>
</body>
</html>`

**Comment by caewok** [comment]
Should be addressed now.
