### ISSUE TITLE
Feature: Add setting to target large tokens by grid space

### ISSUE THREAD

**Issue by caewok** [caewok/fvtt-walled-templates#72]
See https://ptb.discord.com/channels/915186263609454632/1107502968179273778/1163869822573097000

Basically, using area or even points to target large tokens can mean that the large tokens remain untargeted even if a substantial portion of them are within the template. For example, larger tokens could have several grid squares worth of token within the template but still be untargeted. 

Possible solution is to add an option to consider larger tokens to be targeted once the portion within the template exceeds one grid square. For area, this would be based on area of a grid square. For points, this requires testing points per grid square, similar to what is done in Alt. Token Visibility for cover under dnd5e DMG rules.

**Comment by caewok** [comment]
Unneeded because the current targeting activates if any portion of the token is within the template shape.

**Comment by lucky-trill** [comment]
Is there a particular set of settings that makes this unneeded?

Because as far as I can tell, 2 x 2 and larger tokens are frequently left untargeted when a single highlighted square overlaps their space unless you use a proportionally tiny overlap percentage (25% for 2x2, 11% for 3x3, 8% for 4x4), which massively increases what squares the template highlights.

**Comment by lucky-trill** [comment]
As I finally get around to updating my install to v12 and am thus going back to reapply that edits I made to Walled Templated in v11, I'm going to reiterate:

I don't think this is actually closed. Core Walled Templates remains unable to large and tiny tokens accurately based on grid square.

I'll fully concede this is likely somewhat of a "me" issue, because I notice it painfully as I don't use as many small-medium/1x1 tokens as others probably do, but I'm still confident that the closure reason here isn't accurate. It's closeable if small-medium/1x1 targeting is all you really need to be accurate.
